---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent-pyroscope
  labels:
    app: grafana-agent-pyroscope
    name: grafana-agent-pyroscope
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: grafana-agent-pyroscope
  template:
    metadata:
      labels:
        app: grafana-agent-pyroscope
        name: grafana-agent-pyroscope
    spec:
      serviceAccountName: grafana-agent-pyroscope
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: grafana-agent-pyroscope
        image: microbs-grafana-agent-pyroscope
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
        args: [
          "run",
          "/etc/agent/agent.river"
        ]
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AGENT_MODE
          value: flow
        envFrom:
        - secretRef:
           name: microbs-secrets
        volumeMounts:
        - name: data
          mountPath: /etc/agent/data
        - name: tmppositions
          mountPath: /tmp/positions
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: data
        emptyDir: {}
      - name: tmppositions
        hostPath:
          path: /tmp/positions
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-pyroscope
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent-pyroscope
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-pyroscope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent-pyroscope
subjects:
- kind: ServiceAccount
  name: grafana-agent-pyroscope
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent-pyroscope
  namespace: default
  labels:
    app: grafana-agent-pyroscope
    name: grafana-agent-pyroscope
spec:
  ports:
  - port: 12345
    targetPort: 12345
    name: api
  selector:
    name: grafana-agent-pyroscope
