---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-synthetic-monitoring-agent
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana-synthetic-monitoring-agent
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: grafana-synthetic-monitoring-agent
    spec:
      containers:
      - args:
        - /usr/local/bin/synthetic-monitoring-agent --api-server-address=${API_SERVER} --api-token=${PLUGINS_GRAFANA_CLOUD_SYNTHETIC_MONITORING_PROBE_TOKEN} --listen-address=0.0.0.0:4050 --verbose=true
        command:
        - sh
        - -c
        envFrom:
        - secretRef:
           name: microbs-secrets
        env:
        - name: API_SERVER
          value: synthetic-monitoring-grpc.grafana.net:443
        image: grafana/synthetic-monitoring-agent:latest
        name: agent
        ports:
        - containerPort: 4050
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 4050
        livenessProbe:
          httpGet:
            path: /
            port: 4050
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
